name: LebaneseForces
favicon: null
layout_spectrum: 0.8190126761328429
typography_spectrum: 0.6175170596688986
title: Lebanese Forces News
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-8105345-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.8933830559253693
  lightness: 0.6595045840367675
  saturation: 0.032987643731758
  rhythmicContrast: 0.7070475083310157
purpose: []
