name: Lebanese Forces
favicon: null
layout_spectrum: 0.75008
typography_spectrum: 1
title: Lebanese Forces News
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-8105345-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#007639'
    - '#ed1b24'
    - '#ffaaaa'
    - '#58a278'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
